name: "Nvidia Jetson Xavier"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      force-finalize:
        description: Force finalize of the build (implicitly enables hostapp and S3 deployments)
        required: false
        type: boolean
        default: false

permissions:
  id-token: write # This is required for requesting the JWT #https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#requesting-the-access-token
  actions: read # We are fetching workflow run results of a merge commit when workflow is triggered by new tag, to see if tests pass
  pull-requests: write # Read is required to fetch the PR that merged, in order to get the test results. Write is required to create PR comments for workflow approvals.
  packages: read
  contents: read

jobs:
  yocto:
    name: Yocto
    uses: balena-os/balena-yocto-scripts/.github/workflows/yocto-build-deploy.yml@master
    secrets: inherit
    with:
      machine: jetson-xavier
      # Allow manual workflow runs to force finalize without checking previous test runs
      force-finalize: ${{ inputs.force-finalize || false }}
      # This workflow is just for building and then deploying to staging, nothing else
      # This workflow is just for building and then deploying to staging, nothing else
      deploy-environment: balena-staging.com
